### ISSUE TITLE
Expects "identified by" field for Transaction and Event resource types

### ISSUE THREAD

**Issue by theophoric** [hyperledger/composer-vscode-plugin#41]
As of [composer v0.9.0](https://github.com/hyperledger/composer/releases/tag/v0.9.0) transactions and event resources should not define an identifier.  This plugin does not reflect this change.

e.g. The following code:
```

transaction IssueTokens {
  o Long amount
  --> Business recipient
}

```

Generates the following error:

```
file: 'file:////models/fitchain.cto'
severity: 'Error'
message: 'IllegalModelException: line 267 column 1, to line 272 column 2. Class IssueTokens is not declared as abstract. It must define an identifying field.'
at: '267,1'
source: 'Composer'
```

**Comment by m-g-k** [comment]
Hi @theophoric what version of the plugin were you using when you saw the above error? The latest 0.9.1 plugin version has been updated with the Composer v0.9.0 parser and so you need to use this version to use the updated transactions and events syntax that you show above.

**Comment by m-g-k** [comment]
So I have just tested this example transaction with the 0.9.1 plugin version and it does not give an error:
transaction CloseBidding {
  --> VehicleListing listing
}

Therefore I'm closing this as fixed in the current release. If you still see a problem in your setup after updating to the latest version please re-open or raise a new issue. Thanks, MGK
